# site.yml
- name: Setup Web Servers
  hosts: webservers
  become: yes

  vars_files:
    - group_vars/all/vault.yml

  tasks:
    - name: Ping all webservers
      ping:

    - name: Install curl
      apt:
        name: curl
        state: present

  roles:
    - role: webserver

