# roles/webserver/tasks/main.yml
- name: Install Apache
  apt:
    name: apache2
    state: present
  tags: apache

- name: Deploy custom index.html
  template:
    src: index.html.j2
    dest: /var/www/html/index.html
  when: env == "staging"
  notify: Restart Apache
  tags: apache

- name: Ensure Apache is running and enabled
  service:
    name: apache2
    state: started
    enabled: yes
